// Auto-generated from the approved prompt set (v3). Do not hand-edit text here;
// regenerate from the source doc if prompts change.
// 180 prompts: 30 per TTM stage, grouped into 6 chapters each.
// Stable ids (<stage>_<n>) are read by the Mirror and the post-pilot AI reflections.

export const JOURNAL_PROMPTS = {
  notice: [
    { id: 'notice_1', chapter: 'The people who matter', text: `Who matters most to you — and do they know it?` },
    { id: 'notice_2', chapter: 'The people who matter', text: `How do you show someone you care, without saying it?` },
    { id: 'notice_3', chapter: 'The people who matter', text: `Who would you drop everything for?` },
    { id: 'notice_4', chapter: 'The people who matter', text: `When did someone last make you feel truly understood?` },
    { id: 'notice_5', chapter: 'The people who matter', text: `Who do you wish you were closer to?` },
    { id: 'notice_6', chapter: 'Who you are', text: `What are you actually good at — not what you're "supposed" to be good at?` },
    { id: 'notice_7', chapter: 'Who you are', text: `What do people get wrong about you?` },
    { id: 'notice_8', chapter: 'Who you are', text: `What's something you're quietly proud of that you rarely mention?` },
    { id: 'notice_9', chapter: 'Who you are', text: `When do you feel most like yourself?` },
    { id: 'notice_10', chapter: 'Who you are', text: `What's a part of you that you keep to yourself?` },
    { id: 'notice_11', chapter: 'How you got here', text: `What were you like before any of this started?` },
    { id: 'notice_12', chapter: 'How you got here', text: `What did you used to do with the time the habit now takes?` },
    { id: 'notice_13', chapter: 'How you got here', text: `When did it stop being a choice and start being a routine?` },
    { id: 'notice_14', chapter: 'How you got here', text: `What were you really looking for when it began?` },
    { id: 'notice_15', chapter: 'How you got here', text: `What's changed about you that you'd want to change back?` },
    { id: 'notice_16', chapter: 'Being honest', text: `What's one thing you've been avoiding looking at? Just name it here.` },
    { id: 'notice_17', chapter: 'Being honest', text: `What do you tell people about it that isn't the whole truth?` },
    { id: 'notice_18', chapter: 'Being honest', text: `Where and when do urges usually catch you?` },
    { id: 'notice_19', chapter: 'Being honest', text: `When an urge hits, what's the first excuse your mind offers?` },
    { id: 'notice_20', chapter: 'Being honest', text: `What are the ways you've tried to keep it hidden?` },
    { id: 'notice_21', chapter: 'A clearer look', text: `What's something you do that you wish you didn't?` },
    { id: 'notice_22', chapter: 'A clearer look', text: `What's one small thing today that future-you would thank you for?` },
    { id: 'notice_23', chapter: 'A clearer look', text: `What feels heavier than it should right now?` },
    { id: 'notice_24', chapter: 'A clearer look', text: `What's a good habit you already have?` },
    { id: 'notice_25', chapter: 'A clearer look', text: `What do you do when no one's watching that you're glad about?` },
    { id: 'notice_26', chapter: 'The good in today', text: `What's one good thing that happened today?` },
    { id: 'notice_27', chapter: 'The good in today', text: `Who made your day a little better?` },
    { id: 'notice_28', chapter: 'The good in today', text: `What are you looking forward to?` },
    { id: 'notice_29', chapter: 'The good in today', text: `What did you get right today, even if it was small?` },
    { id: 'notice_30', chapter: 'The good in today', text: `What's still good in your life, despite everything?` },
  ],
  reflect: [
    { id: 'reflect_1', chapter: 'Love, given and received', text: `How do you show love? How do you like to receive it?` },
    { id: 'reflect_2', chapter: 'Love, given and received', text: `What did love look like in the house you grew up in — spoken, or shown?` },
    { id: 'reflect_3', chapter: 'Love, given and received', text: `Who loves you in a way you can count on?` },
    { id: 'reflect_4', chapter: 'Love, given and received', text: `When did you last feel really loved?` },
    { id: 'reflect_5', chapter: 'Love, given and received', text: `Who do you find hard to love, and why?` },
    { id: 'reflect_6', chapter: 'The people in your life', text: `Who brings out your best? Who brings out your worst?` },
    { id: 'reflect_7', chapter: 'The people in your life', text: `What does a good friend do — and are you one?` },
    { id: 'reflect_8', chapter: 'The people in your life', text: `Who have you lost touch with that you miss?` },
    { id: 'reflect_9', chapter: 'The people in your life', text: `What do you need from the people close to you that you don't ask for?` },
    { id: 'reflect_10', chapter: 'The people in your life', text: `Who would you forgive, if you let yourself?` },
    { id: 'reflect_11', chapter: 'Who you are', text: `What are you like at your best?` },
    { id: 'reflect_12', chapter: 'Who you are', text: `What's a strength of yours that you play down?` },
    { id: 'reflect_13', chapter: 'Who you are', text: `What's a compliment that stuck with you — and why that one?` },
    { id: 'reflect_14', chapter: 'Who you are', text: `What do you believe that the people around you don't?` },
    { id: 'reflect_15', chapter: 'Who you are', text: `What do you want to be known for?` },
    { id: 'reflect_16', chapter: 'Being honest', text: `When has honesty been hard for you — and what happened?` },
    { id: 'reflect_17', chapter: 'Being honest', text: `How do small lies change how close you feel to someone?` },
    { id: 'reflect_18', chapter: 'Being honest', text: `What's something you're not proud of that you've never told anyone?` },
    { id: 'reflect_19', chapter: 'Being honest', text: `What would you never lie about, no matter what?` },
    { id: 'reflect_20', chapter: 'Being honest', text: `Where are you fooling yourself a little right now?` },
    { id: 'reflect_21', chapter: 'The habit, honestly', text: `What does the habit really cost you, beyond the obvious?` },
    { id: 'reflect_22', chapter: 'The habit, honestly', text: `When you give in, when do you actually decide — before the urge, or after it?` },
    { id: 'reflect_23', chapter: 'The habit, honestly', text: `What good things show up when you get past an urge?` },
    { id: 'reflect_24', chapter: 'The habit, honestly', text: `What would you do with the time and money the habit takes?` },
    { id: 'reflect_25', chapter: 'The habit, honestly', text: `What part of your life would change most if it were gone?` },
    { id: 'reflect_26', chapter: 'What you want', text: `What do you secretly want more of in your life?` },
    { id: 'reflect_27', chapter: 'What you want', text: `What's a dream you put down somewhere along the way?` },
    { id: 'reflect_28', chapter: 'What you want', text: `If you had a free year, what would you do with it?` },
    { id: 'reflect_29', chapter: 'What you want', text: `What would make this a year you're proud of?` },
    { id: 'reflect_30', chapter: 'What you want', text: `What's something good you have that you forget to notice?` },
  ],
  commit: [
    { id: 'commit_1', chapter: 'The people in your corner', text: `Who do you want beside you for the next few weeks?` },
    { id: 'commit_2', chapter: 'The people in your corner', text: `Who would pick up if you called at 9pm on a hard night?` },
    { id: 'commit_3', chapter: 'The people in your corner', text: `Who's already rooting for you, whether they've said so or not?` },
    { id: 'commit_4', chapter: 'The people in your corner', text: `Who's the one person you can be fully honest with?` },
    { id: 'commit_5', chapter: 'The people in your corner', text: `Who do you want to make proud — including yourself?` },
    { id: 'commit_6', chapter: 'Who you want to be', text: `What kind of person do you want to be a month from now?` },
    { id: 'commit_7', chapter: 'Who you want to be', text: `What's a quality you admire in someone you know?` },
    { id: 'commit_8', chapter: 'Who you want to be', text: `What would the best version of you do differently this week?` },
    { id: 'commit_9', chapter: 'Who you want to be', text: `What have you always wanted to be able to say about yourself?` },
    { id: 'commit_10', chapter: 'Who you want to be', text: `What would make you respect yourself more?` },
    { id: 'commit_11', chapter: 'Your why', text: `Why are you really doing this, in plain words?` },
    { id: 'commit_12', chapter: 'Your why', text: `What are you saying *yes* to, by saying no to the habit?` },
    { id: 'commit_13', chapter: 'Your why', text: `What's the cost of *not* changing?` },
    { id: 'commit_14', chapter: 'Your why', text: `Who gets hurt when you don't — and who gains when you do?` },
    { id: 'commit_15', chapter: 'Your why', text: `What do you want to be true by the end of these ten days?` },
    { id: 'commit_16', chapter: 'Getting ready', text: `What excuses will your mind use? Name them so you'll see them coming.` },
    { id: 'commit_17', chapter: 'Getting ready', text: `What's your plan for the first hard moment?` },
    { id: 'commit_18', chapter: 'Getting ready', text: `Where will you most need to say "no thanks" — and what words will you use?` },
    { id: 'commit_19', chapter: 'Getting ready', text: `What's one thing you can change about your surroundings to make it easier?` },
    { id: 'commit_20', chapter: 'Getting ready', text: `What will you do with your hands and your hour when an urge hits?` },
    { id: 'commit_21', chapter: 'The life ahead', text: `What would you love your evenings to be about?` },
    { id: 'commit_22', chapter: 'The life ahead', text: `What's something fun you've been putting off?` },
    { id: 'commit_23', chapter: 'The life ahead', text: `What do you want your mornings to feel like?` },
    { id: 'commit_24', chapter: 'The life ahead', text: `What would a genuinely good week look like for you now?` },
    { id: 'commit_25', chapter: 'The life ahead', text: `What would you do with yourself if the habit just wasn't a thing?` },
    { id: 'commit_26', chapter: 'Looking forward', text: `Who will be glad you did this?` },
    { id: 'commit_27', chapter: 'Looking forward', text: `What's the first thing you want to feel on the other side?` },
    { id: 'commit_28', chapter: 'Looking forward', text: `How will you mark getting through week one?` },
    { id: 'commit_29', chapter: 'Looking forward', text: `What are you most looking forward to about being free of it?` },
    { id: 'commit_30', chapter: 'Looking forward', text: `What would you tell yourself on day one, to keep going?` },
  ],
  endure: [
    { id: 'endure_1', chapter: 'Getting through today', text: `What got you through today?` },
    { id: 'endure_2', chapter: 'Getting through today', text: `What helped when it got hard?` },
    { id: 'endure_3', chapter: 'Getting through today', text: `What's your best way to ride out the first ten minutes of an urge?` },
    { id: 'endure_4', chapter: 'Getting through today', text: `What did you do for yourself today?` },
    { id: 'endure_5', chapter: 'Getting through today', text: `What felt impossible a week ago that's a little easier now?` },
    { id: 'endure_6', chapter: 'The people around you', text: `Who showed up for you this week?` },
    { id: 'endure_7', chapter: 'The people around you', text: `Who could you reach out to today, just because?` },
    { id: 'endure_8', chapter: 'The people around you', text: `Who would be glad to hear from you right now?` },
    { id: 'endure_9', chapter: 'The people around you', text: `What's a kindness someone did for you lately?` },
    { id: 'endure_10', chapter: 'The people around you', text: `What's a kind thing you could do for someone this week?` },
    { id: 'endure_11', chapter: 'Small wins', text: `What did you handle today that you weren't sure you could?` },
    { id: 'endure_12', chapter: 'Small wins', text: `What's a win the old you would've walked right past?` },
    { id: 'endure_13', chapter: 'Small wins', text: `What good thing happened *because* you didn't give in?` },
    { id: 'endure_14', chapter: 'Small wins', text: `What are you a little proud of this week?` },
    { id: 'endure_15', chapter: 'Small wins', text: `What's getting easier?` },
    { id: 'endure_16', chapter: 'Who you\'re becoming', text: `What feels different about you now, even slightly?` },
    { id: 'endure_17', chapter: 'Who you\'re becoming', text: `What's a new part of your day that you actually like?` },
    { id: 'endure_18', chapter: 'Who you\'re becoming', text: `What do you have more room for now?` },
    { id: 'endure_19', chapter: 'Who you\'re becoming', text: `What would you like to do more of?` },
    { id: 'endure_20', chapter: 'Who you\'re becoming', text: `What does feeling steady look like for you?` },
    { id: 'endure_21', chapter: 'What you carry', text: `What's weighing on you that you could share with someone?` },
    { id: 'endure_22', chapter: 'What you carry', text: `Who do you owe a proper conversation?` },
    { id: 'endure_23', chapter: 'What you carry', text: `Who have you been short with that you don't want to be?` },
    { id: 'endure_24', chapter: 'What you carry', text: `What's something you need to forgive yourself for?` },
    { id: 'endure_25', chapter: 'What you carry', text: `What's a worry you could set down today?` },
    { id: 'endure_26', chapter: 'Gratitude', text: `What's one moment from this week you'd want to keep?` },
    { id: 'endure_27', chapter: 'Gratitude', text: `Who in your life are you lucky to have?` },
    { id: 'endure_28', chapter: 'Gratitude', text: `What freedom have you got back that you'd been missing?` },
    { id: 'endure_29', chapter: 'Gratitude', text: `What did your body do for you this week that you're thankful for?` },
    { id: 'endure_30', chapter: 'Gratitude', text: `What's one thing you did this week you'll be glad about later?` },
  ],
  build: [
    { id: 'build_1', chapter: 'The people you love', text: `Which relationship has gotten better, and what did it take?` },
    { id: 'build_2', chapter: 'The people you love', text: `How do you want to show up for the people you love?` },
    { id: 'build_3', chapter: 'The people you love', text: `Who would you like to know more deeply?` },
    { id: 'build_4', chapter: 'The people you love', text: `Who in your life would you like to thank, properly?` },
    { id: 'build_5', chapter: 'The people you love', text: `What does being a good friend, partner, or parent mean to you now?` },
    { id: 'build_6', chapter: 'Who you\'ve become', text: `Who are you now that you weren't six months ago?` },
    { id: 'build_7', chapter: 'Who you\'ve become', text: `What's a part of you that's come back to life?` },
    { id: 'build_8', chapter: 'Who you\'ve become', text: `What are you better at than you used to be?` },
    { id: 'build_9', chapter: 'Who you\'ve become', text: `What do you like about yourself these days?` },
    { id: 'build_10', chapter: 'Who you\'ve become', text: `What would the people who love you say has changed?` },
    { id: 'build_11', chapter: 'What matters now', text: `What gives your weeks meaning?` },
    { id: 'build_12', chapter: 'What matters now', text: `What are you building, beyond just not doing the thing?` },
    { id: 'build_13', chapter: 'What matters now', text: `What do you care about now that you didn't before?` },
    { id: 'build_14', chapter: 'What matters now', text: `What's worth your time, and what isn't anymore?` },
    { id: 'build_15', chapter: 'What matters now', text: `What kind of life are you trying to make?` },
    { id: 'build_16', chapter: 'Giving back', text: `Who's earlier in this than you that you could help?` },
    { id: 'build_17', chapter: 'Giving back', text: `How could you make someone's week better?` },
    { id: 'build_18', chapter: 'Giving back', text: `What have you learned that's worth passing on?` },
    { id: 'build_19', chapter: 'Giving back', text: `Who supported you that you could repay somehow?` },
    { id: 'build_20', chapter: 'Giving back', text: `What would you tell someone on their day one?` },
    { id: 'build_21', chapter: 'Dreams', text: `What do you want to learn, make, or try — just because?` },
    { id: 'build_22', chapter: 'Dreams', text: `What's a dream it might be time to take off the shelf?` },
    { id: 'build_23', chapter: 'Dreams', text: `What would you do with your life if staying free were a settled fact?` },
    { id: 'build_24', chapter: 'Dreams', text: `Where would you go if you could go anywhere, and who with?` },
    { id: 'build_25', chapter: 'Dreams', text: `What do you want the next year to be about?` },
    { id: 'build_26', chapter: 'Gratitude & freedom', text: `What's in your life now that you once weren't sure you'd get back?` },
    { id: 'build_27', chapter: 'Gratitude & freedom', text: `What's the best thing freedom has given you?` },
    { id: 'build_28', chapter: 'Gratitude & freedom', text: `What's good in your life that has nothing to do with any of this?` },
    { id: 'build_29', chapter: 'Gratitude & freedom', text: `What did you used to mourn that you have back now?` },
    { id: 'build_30', chapter: 'Gratitude & freedom', text: `What would you be sad to lose, now that you have it?` },
  ],
  reclaim: [
    { id: 'reclaim_1', chapter: 'Be kind to yourself', text: `What would you say to a good friend in your exact spot? Now say it to yourself.` },
    { id: 'reclaim_2', chapter: 'Be kind to yourself', text: `What do you need most today?` },
    { id: 'reclaim_3', chapter: 'Be kind to yourself', text: `Where are you being harder on yourself than you deserve?` },
    { id: 'reclaim_4', chapter: 'Be kind to yourself', text: `What's one kind thing you can do for yourself today?` },
    { id: 'reclaim_5', chapter: 'Be kind to yourself', text: `What would it take to forgive yourself, even a little?` },
    { id: 'reclaim_6', chapter: 'Who\'s still there', text: `Who loves you, no matter what?` },
    { id: 'reclaim_7', chapter: 'Who\'s still there', text: `Who would meet you with kindness right now, if you let them?` },
    { id: 'reclaim_8', chapter: 'Who\'s still there', text: `Who's safe enough to be a mess around?` },
    { id: 'reclaim_9', chapter: 'Who\'s still there', text: `Is there someone you pulled away from that you could reach back to?` },
    { id: 'reclaim_10', chapter: 'Who\'s still there', text: `Who would you want beside you, if they knew the truth?` },
    { id: 'reclaim_11', chapter: 'What still stands', text: `What didn't this take from you?` },
    { id: 'reclaim_12', chapter: 'What still stands', text: `Why did you start this in the first place — and is it still true?` },
    { id: 'reclaim_13', chapter: 'What still stands', text: `What are you still grateful you get to do?` },
    { id: 'reclaim_14', chapter: 'What still stands', text: `What's one thing you like about yourself, slip and all?` },
    { id: 'reclaim_15', chapter: 'What still stands', text: `What's still worth it here?` },
    { id: 'reclaim_16', chapter: 'Coming back', text: `What's the next right thing — just the next one?` },
    { id: 'reclaim_17', chapter: 'Coming back', text: `What helped you come back last time?` },
    { id: 'reclaim_18', chapter: 'Coming back', text: `What would the next 24 hours look like, gently?` },
    { id: 'reclaim_19', chapter: 'Coming back', text: `What's one thing you can take off your plate today?` },
    { id: 'reclaim_20', chapter: 'Coming back', text: `What caught you off guard this time, that you'll catch sooner next?` },
    { id: 'reclaim_21', chapter: 'What you\'ve learned', text: `What was the hardest part of today, honestly?` },
    { id: 'reclaim_22', chapter: 'What you\'ve learned', text: `What were you really needing when it happened?` },
    { id: 'reclaim_23', chapter: 'What you\'ve learned', text: `What would you do differently, with no blame attached?` },
    { id: 'reclaim_24', chapter: 'What you\'ve learned', text: `What does this tell you about what you need more of?` },
    { id: 'reclaim_25', chapter: 'What you\'ve learned', text: `What's a gentler way to talk to yourself about it?` },
    { id: 'reclaim_26', chapter: 'A little forward', text: `What's something good waiting on the other side of this?` },
    { id: 'reclaim_27', chapter: 'A little forward', text: `What are you looking forward to, even faintly?` },
    { id: 'reclaim_28', chapter: 'A little forward', text: `What's a kindness you've done for someone lately?` },
    { id: 'reclaim_29', chapter: 'A little forward', text: `What made you smile recently, even for a second?` },
    { id: 'reclaim_30', chapter: 'A little forward', text: `What would your steadier, future self tell you today?` },
  ],
}

// Distinct chapter order (first appearance) for a stage — drives deterministic rotation.
export function chaptersFor(stage) {
  const seen = []
  for (const p of (JOURNAL_PROMPTS[stage] || [])) {
    if (!seen.includes(p.chapter)) seen.push(p.chapter)
  }
  return seen
}